### ISSUE TITLE
License for this?

### ISSUE THREAD

**Issue by eoinmurray** [dropbox/dropbox-api-v2-explorer#2]
Is it okay to use this in my own project, adapt it to another API except dropbox?

**Comment by eoinmurray** [comment]
Is it okay to use this in my own project, adapt it to another API except dropbox?

**Comment by cakoose** [comment]
It's MIT-licensed, so yeah, you can adapt it to another API (I just added a License.txt file.)

**Comment by eoinmurray** [comment]
Great thanks.
