### ISSUE TITLE
Code View of API calls does not update

### ISSUE THREAD

**Issue by rogebrd** [dropbox/dropbox-api-v2-explorer#22]
Upon updating a parameter or the code view type, the request view should re-render and show the updated request it is making.  However, due to changes in the way react has been updated, this now does not work.  

I suspect that this is due to the fact that when the parent re-renders upon state change, it was previously recreating the react components instead of reusing them like it does today.  The recreation was what was updating them in the past and therefore the parent updating needs to be passed down to the children now.

**Comment by greg-db** [comment]
Thanks for reporting this Brad.

**Comment by KarandeepJohar** [comment]
#26
