### ISSUE TITLE
Live Demo doesn't work

### ISSUE THREAD

**Issue by krebbl** [dropbox/dropbox-api-v2-explorer#3]
The Live demo doesn't work. Seems like the libraries can't be loaded from cloudflare.

**Comment by greg-db** [comment]
@krebbl The live demo seems to be working for me. If you're still seeing this issue, can you share the steps to reproduce it and the error you're getting, or a screenshot? Thanks in advance!

**Comment by krebbl** [comment]
@greg-db its now working again. maybe it was a DNS problem on my side.
