### ISSUE TITLE
Register a webhook dynamically

### ISSUE THREAD

**Issue by theteladras** [dropbox/dropbox-api-v2-explorer#314]
I can't find an information, on wether there is a way to programmatically register webhooks.

Is there a way to register a webhook through an API request? This would be very useful, in cases where we have oAuth users and wish to setup webhooks for them, currently to make it work each user would have to go through the console and do it manually. Maybe this is something that is coming shortly in the future?

**Comment by greg-db** [comment]
Dropbox does not offer the ability to register webhook URIs programmatically, but I'll pass this along as a feature request. I can't promise if or when that might be implemented though. 

Note though that the end-users of your app shouldn't each be registering their own app and webhook URI(s). You as the developer would register your app and webhook URI(s) once, and then you would recieve webhook notifications to the webhook URI(s) for any changes in any of the user accounts connected to your app.

Please refer to the following resources for more information:

- https://developers.dropbox.com/oauth-guide
- https://www.dropbox.com/developers/reference/webhooks

**Comment by theteladras** [comment]
Hey @greg-db

Thanks for the reply!

I understand, did not think of it that way. Usually when it comes to webhooks, you register specific urls for users (_maybe even multiple_). But yes, your answer solves my quest!

Best wishes!
