### ISSUE TITLE
list_shared_links not working

### ISSUE THREAD

**Issue by axew3** [dropbox/dropbox-api-v2-explorer#6]
Hi all, i reported this problem months ago via dropbox official support ticket, a problem about **list_shared_links** that not return correct results: it affect calls done via curl, in php, javascript library and even on online api explorer i experienced. But after some answer, lot of time passed and still no answers, but " team is looking to resolve"
Anybody know when somebody will take a look into this end point when ever would be possible to resolve this issue?
The bug resumed cause this:
let say there are in sharing 2000 files and related folders: calling list_shared_links the result is that only some files are retrieved and only one folder (the last created folder with some files for example).

P.s do not think this is exactly the right place to put this

**Comment by greg-db** [comment]
@axew3 Your support ticket is still open with engineering, though unfortunately I don't have a timeline for a fix right now. 

As this issue is not related to the API Explorer itself, I'm closing this in favor of your existing support ticket. We'll follow up on your ticket when we have an update for you.

**Comment by axew3** [comment]
sorry lost this .... 
??? 
> As this issue is not related to the API Explorer itself
it isn't a dbx endpoint that not work ok?
May this is not an update for me, but for all developers which think to do something with dbx api.
Best regards

**Comment by greg-db** [comment]
@axew3 You are referring to a problem with the Dropbox API endpoint /2/sharing/list_shared_links itself. You have an open Dropbox support ticket for that request. Your ticket is open with engineering, so you do not need to post here regarding it.

I closed this extraneous GitHub issue, as you opened it for the "dropbox-api-v2-explorer" project, which is just a tool for calling the Dropbox API.

**Comment by axew3** [comment]
Ok thank you by the way, 
so i see that unfortunately no updates on
list_shared_links endpoint 
have been done. Regards
